#!/bin/bash
#
### Set lesson based on LESSON_ACCOUNT
#
  lesson_accounts=`cat /jbasedata/LESSON_ACCOUNT`
  set -- $lesson_accounts
  main_account=$1
  shift
  extra_accounts="$@"
#
### if root user, start processes
#
  if [ "$(id -u)" -eq 0 ];then
#
### Adding license for 4
#
    jbase_host=`hostname`
    if [ "$jbase_host" = "jbase" ]; then
      /opt/jbase/CurrentVersion/bin/jlicenseupdate -force -add \
BFNOPTYyNDk1NjY0LFZTPTYuMi4yLjYsVVM9NixITj1qYmFzZSxFWD0yMy0wNS0yMDI4LEpBLE9ELEpSLEFMLERMLEVOABsXWuO3gSgADqqzP7BFb7T4FGmctAIQebJletrL4YXOzOZV/2pSf+wwsoYMHTF+NdQ+eiUdJrgPSxHxR4TrPfgZnXgAofSlLgnIHCFLJigGGrPR+gFYazk+MWwPxlMhTAVbuHjyiZA2Fo/tMk6Q5Gxb5yfJcmi4TxS894SiiS6IioN3nvDnxToVYfvqsb3yrXt/UgD5UnIp076KZHPYDSR3EfiCnL51+LUd9Uk9jvH74n1s2TGldODzpYEPrTTUXpRFHhw0nUz8HBg7f/CLgiUYNZK/6GYx8uRdoZS0rW+QMgbgigbO4p4GzCs9SDk4wvU4gPXsyxgdTWK+UFOkGeQ=
    fi
#
### Check if telnet is up, and if not, start it
#
    telnetup=`ps -ef | grep telnetd | grep -v -e grep`
    if [ -z "$telnetup" ]; then
      echo 'Starting telnet process'
      busybox telnetd -p 23 -l /bin/login &
    else
      echo 'telnet is up'
    fi
#
### Start jDLS
#
    echo Starting jDLS lock daemon
    /opt/jbase/CurrentVersion/bin/jDLS -ibAP
#
### Start jbase agent for VSCode
#
    echo Starting jbase_agent
    nohup /opt/jbase/CurrentVersion/bin/jbase_agent -L4 -A none > /tmp/jbase_agent.log 2>&1 &
#
### Set JBASE_DISABLE_DEVELOPER_LICENSE_WARNING to remove message
#
    export JBASE_DISABLE_DEVELOPER_LICENSE_WARNING=1
#
### If no external volume as /mystuff, create /mystuff directory
#
    if [ ! -d /mystuff ]; then
      printf "Creating internal mystuff directory"
      mkdir -m777 /mystuff
      printf "\nThe $main_account account will not remain when docker run is complete.\n"
      echo -e "\e[7m⚠ CHANGES TO the $main_account WILL BE LOST WHEN THIS CONTAINER EXITS!\e[0m"
      printf "\nIf you want to keep your own copy of the $main_account you must run docker with -v option\n"
    fi
#
### Change directory to /mystuff regardless of origin
#
    printf "Changing to /mystuff directory\n"
    cd /mystuff
#
### If jbase_config.json exists, move it to /opt/jbase/global/config
#
    if [ -f "/mystuff/jbase_config.json" ]; then
      printf "\nUSING jbase_config.json IN /mystuff\n"
      cp /mystuff/jbase_config.json /opt/jbase/global/config/.
    fi
#
### Create environment if needed -- first time
#
    if [ ! -d "/mystuff/$main_account" ]; then
      printf "Loading accounts for the lesson\n"
      tar -xzpf /jbasedata/lesson.tar.gz 2> /dev/null
      /opt/jbase/CurrentVersion/bin/create-account /mystuff/$main_account -f
      printf "BASIC/CATALOG FRED.BP utilities in $main_account\n"
      /opt/jbase/CurrentVersion/bin/jsh -a$main_account -c"BASIC FRED.BP *"
      /opt/jbase/CurrentVersion/bin/jsh -a$main_account -c"CATALOG FRED.BP *"
      if [ -z "$extra_accounts" ]; then
        printf "This is a single account lesson\n"
      else
        for account_name in $extra_accounts ; do
          /opt/jbase/CurrentVersion/bin/create-account /mystuff/$account_name -f
          printf "BASIC/CATALOG FRED.BP utilities in $account_name\n"
          /opt/jbase/CurrentVersion/bin/jsh -a$account_name -c"BASIC FRED.BP *"
          /opt/jbase/CurrentVersion/bin/jsh -a$account_name -c"CATALOG FRED.BP *"
        done
      fi
    else
#
### Already exists, but need to create account into SYSTEM file
#
      /opt/jbase/CurrentVersion/bin/create-account /mystuff/$main_account -f
      if [ ! -n "$extra_accounts" ]; then
        for account_name in $lesson_accounts ; do
          /opt/jbase/CurrentVersion/bin/create-account /mystuff/$account_name -f
        done
      fi
    fi
#
### Always change permissions and ownership if set to 12000:12000
#
    printf "Adjusting permissions and ownership for the accounts\n"
    find /mystuff -uid 12000 -gid 12000 \
     -exec chown jbaseadm:jbase {} + \
     -exec chmod 777 {} +
#
# start jBASE session in lesson account
#
    if [ -f "/mystuff/jbase_config.json" ]; then
      printf "\nUSING jbase_config.json IN /mystuff\n"
      cp /mystuff/jbase_config.json /opt/jbase/global/config/.
    fi
    echo "Running as root, changing to user user1"
    su - user1
  else
    printf "Setting umask to 002\n"
    umask 002
    printf "Changing backspace\n"
    stty erase ^h
    echo "Running jBASE session"
    /opt/jbase/CurrentVersion/bin/jlogin $main_account
  fi
